language_codes = [
    {"language": "Afrikaans", "iso": "afr"},
    {"language": "Arabic", "iso": "ara"},
    {"language": "Aragonese", "iso": "arg"},
    {"language": "Asturian", "iso": "ast"},
    {"language": "Belarusian", "iso": "bel"},
    {"language": "Bosnian", "iso": "bos"},
    {"language": "Bulgarian", "iso": "bul"},
    {"language": "Catalan", "iso": "cat"},
    {"language": "Valencian", "iso": "cat_valencia"},
    {"language": "Crimean Tatar", "iso": "crh"},
    {"language": "Croatian", "iso": "hrv"},
    {"language": "Danish", "iso": "dan"},
    {"language": "Dutch", "iso": "nld"},
    {"language": "English", "iso": "eng"},
    {"language": "Esperanto", "iso": "epo"},
    {"language": "French", "iso": "fra"},
    {"language": "Galician", "iso": "glg"},
    {"language": "Hindi", "iso": "hin"},
    {"language": "Icelandic", "iso": "isl"},
    {"language": "Indonesian", "iso": "ind"},
    {"language": "Italian", "iso": "ita"},
    {"language": "Kazakh", "iso": "kaz"},
    {"language": "Macedonian", "iso": "mkd"},
    {"language": "Malay", "iso": "msa"},
    {"language": "Maltese", "iso": "mlt"},
    {"language": "Norwegian Bokmal", "iso": "nob"},
    {"language": "Norwegian Nynorsk", "iso": "nno"},
    {"language": "Occitan", "iso": "oci"},
    {"language": "Aranese", "iso": "oci_aran"},
    {"language": "Polish", "iso": "pol"},
    {"language": "Portuguese", "iso": "por"},
    {"language": "Brazilian Portuguese", "iso": "por_BR"},
    {"language": "Russian", "iso": "rus"},
    {"language": "Sardinian", "iso": "srd"},
    {"language": "Serbian", "iso": "srp"},
    {"language": "Silesian", "iso": "szl"},
    {"language": "Slovenian", "iso": "slv"},
    {"language": "Spanish", "iso": "spa"},
    {"language": "Swedish", "iso": "swe"},
    {"language": "Tatar", "iso": "tat"},
    {"language": "Turkish", "iso": "tur"},
    {"language": "Ukrainian", "iso": "ukr"},
    {"language": "Urdu", "iso": "urd"},
    {"language": "Welsh", "iso": "cym"},
    {"language": "Serbo-Croatian", "iso": "hbs"},
    {"language": "Basque", "iso": "eus"},
    {"language": "Romanian", "iso": "ron"},
    {"language": "American English", "iso": "eng_US"},
    {"language": "Breton", "iso": "bre"}
    ]
